CREATE TABLE IF NOT EXISTS articles_content (

  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  article_id INT(11) NOT NULL,
  language INT(4) DEFAULT -1 NOT NULL,
  title VARCHAR(128) NOT NULL,
  excerpt VARCHAR(384) DEFAULT '' NOT NULL,
  url VARCHAR(128) NOT NULL,
  perex_date DATETIME DEFAULT NULL,
  perex_location VARCHAR(128) DEFAULT '' NOT NULL,
  tags JSON DEFAULT NULL,
  categories JSON DEFAULT NULL,
  custom_fields JSON DEFAULT NULL,
  meta_keywords VARCHAR(1024) DEFAULT '',
  meta_description VARCHAR(1024) DEFAULT '',
  sources JSON DEFAULT NULL,
  content JSON DEFAULT NULL,
  prerender LONGTEXT DEFAULT NULL,

  FOREIGN KEY (article_id) REFERENCES articles(id)

) AUTO_INCREMENT 1
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;