CREATE TABLE IF NOT EXISTS attachments (

  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  article_id INT(11) NOT NULL,
  type INT(6) NOT NULL DEFAULT 0,
  attachment VARCHAR(256) NOT NULL,

  FOREIGN KEY (article_id) REFERENCES articles(id)

) AUTO_INCREMENT 1
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;