CREATE TABLE IF NOT EXISTS categories (

  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  url VARCHAR(128) NOT NULL,
  parent INT(11) DEFAULT NULL,
  description TINYTEXT DEFAULT NULL,
  thumbnail VARCHAR(256) DEFAULT NULL,
  visibility INT(2) DEFAULT 0,
  count INT(11) DEFAULT 0 NOT NULL

) AUTO_INCREMENT 1
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;