CREATE TABLE IF NOT EXISTS logins (

  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT(11) NOT NULL,
  hash VARCHAR(128) NOT NULL,
  `key` VARCHAR(256) NOT NULL,
  ip VARCHAR(32) NOT NULL,
  ua VARCHAR(256) NOT NULL,
  active BOOLEAN DEFAULT TRUE,
  created TIMESTAMP DEFAULT current_timestamp,
  updated TIMESTAMP DEFAULT current_timestamp ON UPDATE current_timestamp,
  inc INT(11) NOT NULL DEFAULT 0,

  FOREIGN KEY (user_id) REFERENCES users(id)

) AUTO_INCREMENT 1
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;