CREATE TABLE IF NOT EXISTS login_attempts (

  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT(11) NOT NULL,
  created TIMESTAMP DEFAULT current_timestamp,

  FOREIGN KEY (user_id) REFERENCES users(id)

) AUTO_INCREMENT 1
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;