CREATE TABLE IF NOT EXISTS user_settings (

  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT(11) NOT NULL,
  language INT(4) DEFAULT 0 NOT NULL,
  theme INT(4) DEFAULT 0 NOT NULL,

  FOREIGN KEY (user_id) REFERENCES users(id)

) AUTO_INCREMENT 1
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;