CREATE TABLE IF NOT EXISTS website (

  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(45) NOT NULL,
  description VARCHAR(120) NOT NULL,
  category INT(4) DEFAULT 0 NOT NULL,
  send_stats INT(1) DEFAULT 0

) AUTO_INCREMENT 1
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;